image: node:16.15.0
pipelines:
  branches:
    main:
      #for server
      - step:
          name: "Tesing on server"
          caches:
            - node
          script:
            - cd packages/backend
            - npm install --legacy-peer-deps
            - npm install -g jest
            - npm run test
      #for seller
      - step:
          name: "Testing on seller"
          caches:
            - node
          script:
            - cd packages/seller
            - npm install --legacy-peer-deps
            - npm run test
      - step:
          name: "Deploy to heroku"
          caches:
            - node
          script:
            - cd packages/backend
            - git init
            - git config --global user.email "phirunoemark123@gmail.com"
            - git config --global user.name "Phirun Oem"
            - git add .
            - git commit -m "deploy latest update"
            - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master
