image: atlassian/default-image:3

pipelines:
  default:
    - step:
        name: "testing on server"
        caches:
          - node
        script:
          - cd packages/backend
          - yarn install
          - yarn run test
    - step:
        name: "deploy to heroku"
        caches:
          - node
        script:
          - cd packages/backend
          - git init
          - git config --global user.email "phirunoemark123@gmail.com"
          - git config --global user.name "Phirun Oem"
          - git add .
          - git commit -m "deploy latest update"
          - git push -f https://heroku:43188057-4083-4a4b-a59d-2b517e38ad96@git.heroku.com/frugalitybook.git HEAD:master
